authors:
  - caribouHY
namespace: caribouhy
name: sir
version: 1.2.0
readme: README.md
description: Ansible collection for Si-R series
license_file: "LICENSE"
repository: https://github.com/caribouHY/ansible_sir
issues: https://github.com/caribouHY/ansible_sir/issues
tags: [networking]
dependencies:
  "ansible.netcommon": ">=6.1.0"
build_ignore:
  - .vscode
  - tests
